name: Bump version
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag - v2
      run: .github/workflows/auto-increment-version.sh
      shell: bash
        
  
